server:
  port: 8321
  name: 52inc lolcommits
  baseUrl: http://r0adkll.com:8321/public

database:
  name: lol52
  address: localhost
  username: admin
  password: spacebacon

storage:
  local:
    path: images/

  s3:
    access: something
    secret: somethingMore
    bucket: someBucket

  ftp:
    host: http://r0adkll.com
    port: 2020
    user: r0adkll
    pass: spacebacon

  sftp:
    host: http://r0adkll.com
    port: 22
    user: r0adkll
    pass: spacebacon

  imgur:
    apitoken: a3skjdpfoijvpdoiujfp@#$&jpoiuPODIUFPOS234fsiufsoi5foPIJjopFDSOJ

slack:
  url: https://hooks.slack.com/services/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

plugins:
  - storage-local
  - database
  - slack




